--
SELECT condition, 
COUNT(PATIENT_ID) AS TOTAL_PATIENTS
FROM PATIENTS
GROUP BY condition
ORDER BY TOTAL_PATIENTS DESC;


SELECT MEDICATION_NAME,
COUNT(PRESCRIPTION_ID) AS PRESCRIPTION_COUNT
FROM PRESCRIPTIONS
GROUP BY MEDICATION_NAME
ORDER BY PRESCRIPTION_COUNT DESC;


SELECT
    A.DOCTOR_ID,
    A.FIRST_NAME,
    A.LAST_NAME,
    COUNT(B.APPOINTMENT_ID) AS APPOINTMENT_COUNT
FROM DOCTORS A
LEFT JOIN APPOINTMENTS B
    ON A.DOCTOR_ID = B.DOCTOR_ID
GROUP BY A.DOCTOR_ID, A.FIRST_NAME, A.LAST_NAME
ORDER BY APPOINTMENT_COUNT DESC;

SELECT 
    (SUM(CASE WHEN DISCHARGED = 'true' THEN 1 ELSE 0 END)/COUNT(*)) * 
    100.00 AS TRUE_PCT
FROM PATIENTS;

SELECT
    A.DOCTOR_ID,
    A.FIRST_NAME,
    A.LAST_NAME,
    A.EXPERIENCE,
    COUNT(B.PATIENT_ID) AS PATIENT_COUNT,
    SUM(CASE WHEN B.OUTCOME = 'Improved' THEN 1 ELSE 0 END) AS IMPROVED_COUNT,
    ROUND(
        (SUM(CASE WHEN B.OUTCOME = 'Improved' THEN 1 ELSE 0 END)*100.0)/
        NULLIF(COUNT(B.PATIENT_ID),0),
        2
   ) AS IMPROVED_PCT
FROM DOCTORS A
LEFT JOIN APPOINTMENTS B
    ON A.DOCTOR_ID = B.DOCTOR_ID
GROUP BY A.DOCTOR_ID, A.FIRST_NAME, A.LAST_NAME, A.EXPERIENCE
ORDER BY IMPROVED_PCT desc;
